// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-variants/CenteredMinimal.tsx": () => import("../components/mockups/login-variants/CenteredMinimal.tsx"),
  "./components/mockups/login-variants/DarkBillboard.tsx": () => import("../components/mockups/login-variants/DarkBillboard.tsx"),
  "./components/mockups/login-variants/SocialProofLed.tsx": () => import("../components/mockups/login-variants/SocialProofLed.tsx"),
  "./components/mockups/login-variants/WorkflowStory.tsx": () => import("../components/mockups/login-variants/WorkflowStory.tsx")
};
