"""Build hiddenmuseum/i18n.js from strings.py + runtime.js.

    python3 tools/i18n/build.py

Edit the texts in strings.py (HTML: page elements, ATTR: attributes,
JS: texts drawn by app.js), then run this script. With --annotate it also
adds data-i18n attributes to new elements in index.html whose current
English text matches an entry; already-tagged elements are left alone.
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from strings import HTML, ATTR, JS  # noqa: E402

LANGS = ['en', 'fr', 'ar', 'es']
SITE = os.path.join(HERE, '..', '..', 'hiddenmuseum')

strings = {l: {} for l in LANGS}
for k, *vals in HTML + JS:
    for l, v in zip(LANGS, vals):
        strings[l][k] = v
for k, _attr, *vals in ATTR:
    for l, v in zip(LANGS, vals):
        strings[l][k] = v


def add_attr(src, start, name, value):
    end = src.index('>', start)
    tag = src[start:end]
    if f' {name}="' in tag:
        if name == 'data-i18n' or f':{value.split(":", 1)[1]}' in tag:
            return src, False
        m = re.search(name + r'="([^"]*)"', tag)
        return src[:start] + tag.replace(m.group(0), f'{name}="{m.group(1)};{value}"') + src[end:], True
    nm = re.match(r'<[a-zA-Z0-9]+', tag).end()
    return src[:start] + tag[:nm] + f' {name}="{value}"' + tag[nm:] + src[end:], True


if '--annotate' in sys.argv:
    path = os.path.join(SITE, 'index.html')
    src = open(path, encoding='utf-8').read()
    for k, en, *_ in HTML:
        needle, pos = '>' + en + '<', 0
        while (i := src.find(needle, pos)) >= 0:
            st = src.rfind('<', 0, i + 1)
            src, _ = add_attr(src, st, 'data-i18n', k)
            pos = src.find(needle, st) + len(needle)
    for k, attr, en, *_ in ATTR:
        needle, pos = f'{attr}="{en}"', 0
        while (i := src.find(needle, pos)) >= 0:
            st = src.rfind('<', 0, i)
            src, _ = add_attr(src, st, 'data-i18n-attr', f'{attr}:{k}')
            pos = src.find(needle, st) + len(needle)
    open(path, 'w', encoding='utf-8').write(src)

runtime = open(os.path.join(HERE, 'runtime.js'), encoding='utf-8').read()
out = ('/* Musées de Bank Al-Maghrib — interface translations.\n'
       '   Generated by tools/i18n/build.py from tools/i18n/strings.py; do not edit by hand. */\n'
       'window.BAM_STRINGS = ' + json.dumps(strings, ensure_ascii=False, indent=1) + ';\n' + runtime)
open(os.path.join(SITE, 'i18n.js'), 'w', encoding='utf-8').write(out)
print(f'i18n.js: {len(strings["en"])} keys x {len(LANGS)} languages')
